stages:
  - install
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .yarn
    - .playwright
    - node_modules

default:
  image: mcr.microsoft.com/playwright:v1.28.0-focal

install:
  stage: install
  script:
    - yarn install --frozen-lockfile
    - npx playwright install

flight booking tests:
  stage: test
  variables:
    PLAYWRIGHT_HTML_REPORT: flight-booking-test-report/
  script:
    - yarn test
  artifacts:
    when: always
    paths:
      - ${PLAYWRIGHT_HTML_REPORT}
    expire_in: 1 week

