name: Playwright portfolio test
on: 
  push:
    branches: 
      - 'main' 
  schedule:
    - cron: '0 8 * * *'
    
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.yarn
          key: deps-node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit !='true'
        run: yarn ci
        
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - name: run e2e tests
        run: yarn test

      - name: Upload report
        uses: actions/upload-artifact@v3
        if: alywas()
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 1
